config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "vehicles#index"

  resources :vehicles do
    collection { post :import }
    collection { get  :download_csv }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :vehicles, dependent: :destroy

  validates :email, presence: true
  validates :name, presence: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  require 'csv'
  belongs_to :user

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      next if row[0] == 'name' || row[0] == nil

      user_hash = {name: row['name'], nationality: row['nationality'], email: row['email']}
      user = User.create!(user_hash)

      vehicle_hash = {model: row['model'], year: row['year'], color: row['color'], chassis_number: row['chassis_number'], registration_date: row['registration_date'], odometer_reading: row['odometer_reading'], user_id: user.id}
      Vehicle.create!(vehicle_hash)
    end
  end

  def self.to_csv
    attributes = %w{Nationality customers_count}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      User.pluck(:nationality).uniq.each do |nationality|
        user_count = User.where(nationality: nationality).count
        csv << [nationality, user_count]
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    if params[:search].present?
      @vehicles = Vehicle.where(model: params[:search])
      @vehicles = Vehicle.joins(:user).where(users: {name: params[:search]}) if @vehicles.blank?
    else
      @vehicles = Vehicle.all
    end
  end

  def import
    Vehicle.import(params[:file])
    redirect_to root_path
  end

  def download_csv
    respond_to do |format|
      format.html
      format.csv { send_data Vehicle.to_csv, filename: "vehicles-#{Date.today}.csv" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvDemoTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/index.html.erb
<br>
<h1>Vehicle And Users Data</h1>

<div class="page-button">
  <%= form_tag(vehicles_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search], placeholder: "Search by name or model") %>
    <%= submit_tag "Search!" %>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Nationality</th>
      <th scope="col">Email</th>
      <th scope="col">Model</th>
      <th scope="col">Year</th>
      <th scope="col">Chassis Number</th>
      <th scope="col">Color</th>
      <th scope="col">Registration Date</th>
      <th scope="col">Odometer Reading</th>
    </tr>
  </thead>
  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.user.name %></td>
        <td><%= vehicle.user.nationality %></td>
        <td><%= vehicle.user.email %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.chassis_number %></td>
        <td><%= vehicle.color %></td>
        <td><%= vehicle.registration_date %></td>
        <td><%= vehicle.odometer_reading %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<span class="download-txt">
  Download CSV for number of customers by nationality
</span>
<div class="page-button">
  <%= button_to download_csv_vehicles_path(format: "csv"), method: :get, class: 'btn-navbar' do %>
    <i class="fa fa-download" aria-hidden="true"> Download</i></button>
  <% end %>
</div>

<h1>Import the data!</h1>
<%= form_tag import_vehicles_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>